name: python-package

on:
    release:
        types: [published]
    
jobs:
    deploy:
        strategy:
            matrix:
                os: ["ubuntu-latest"]
                python-version: [3.10]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install from source
              shell: pwsh
              run: |
                python -m pip install --upgrade pip
                python -m pip install --upgrade setuptools wheel twine
                python -m pip install -e .
            
            - name: Build
              shell: pwsh
              run: |
                python setup.py sdist bdist_wheel

            - name: Publish to PyPI
              env:
                TWINE_USERNAME: __token__
                TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
              run: |
                python -m twine upload --repository pypi dist/*