name: Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    
jobs:
    TestBPETokenizer:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ["3.9", "3.10", "3.11"]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                    python-version: ${{ matrix.python-version }}
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
                pip install regex

            - name: Run Tests
              run: |
                python -m pytest tests/test_tokenizer.py

            - name: Upload Test Results
              uses: actions/upload-artifact@v4
              with:
                    name: test-results
                    path: test-results.xml
                